version: "3.7"
services:
  verification-service:
    build:
      context: ./verification-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"

  repository-service:
    build:
      context: ./repository-service
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://username:password@host:port/dbname"
        VERIFICATION_SERVICE_URL: "http://verification-service:3005"
    ports:
      - "3000:3000"
