env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings: {
  'import/resolver': {
    node: {
      extensions: ['.js', '.ts'],
      moduleDirectory: ['node_modules', './'],
    },
  },
}
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - src/graphql/types/types.ts
rules: {
  'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        ts: 'never',
      },
    ],
    'linebreak-style': 0,
    'no-console': [0],
    'no-tabs': ['error', { allowIndentationTabs: true }],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'ignore',
      },
    ],
    indent: [
      'error',
      2,
      {
        SwitchCase: 1,
        ignoredNodes: ['ConditionalExpression'],
      },
    ],
    'no-underscore-dangle': 'off',
    'no-param-reassign': 'off',
    'import/prefer-default-export': 'off',
    'import/no-extraneous-dependencies': 'off',
    'class-methods-use-this': 'off',
    'consistent-return': 'off',
    'default-case': 'off'
}